apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-api-config
data:
  ASPNETCORE_HTTP_PORTS: "8080"
  ASPNETCORE_ENVIRONMENT: Production
  RabbitMQ__Host: rabbitmq
  RabbitMQ__Port: "5672"
  PaymentProcessing__ApprovalPercentage: "80"
  PaymentProcessing__DefaultPaymentType: CreditCard
