apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-consumer
  template:
    metadata:
      labels:
        app: catalog-consumer
    spec:
      initContainers:
        - name: wait-for-rabbitmq
          image: busybox:1.36
          command: ['sh', '-c', 'until nc -z rabbitmq 5672; do echo waiting for rabbitmq; sleep 2; done']
      containers:
        - name: catalog-consumer
          image: gpaschoal/cloudgamefiapcatalogconsumer:1.0
          imagePullPolicy: Always
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          envFrom:
            - configMapRef:
                name: catalog-consumer-config
            - secretRef:
                name: catalog-consumer-secret
          livenessProbe:
            exec:
              command:
                - pgrep
                - -f
                - dotnet
            initialDelaySeconds: 20
            periodSeconds: 20
            failureThreshold: 3