apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-api
  template:
    metadata:
      labels:
        app: user-api
    spec:
      initContainers:
        - name: wait-for-rabbitmq
          image: busybox:1.36
          command: ['sh', '-c', 'until nc -z rabbitmq 5672; do echo waiting for rabbitmq; sleep 2; done']
        - name: wait-for-sqlserver
          image: busybox:1.36
          command: ['sh', '-c', 'until nc -z sqlserver 1433; do echo waiting for sqlserver; sleep 2; done']
      containers:
        - name: user-api
          image: dpsnbsb79/cloudgamefiapuserapi:1.0
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: user-api-config
            - secretRef:
                name: user-api-secret