apiVersion: v1
kind: Secret
metadata:
  name: notification-api-secret
type: Opaque
stringData:
  RabbitMq__Host: "rabbitmq"
  RabbitMq__Port: "5672"
  RabbitMq__Username: "admin"
  RabbitMq__Password: "admin123"
