apiVersion: v1
kind: Secret
metadata:
  name: payment-api-secret
type: Opaque
stringData:
  ConnectionStrings__CloudGameDb: Server=sqlserver,1443;Database=CloudGamePaymentsDB;User Id=sa;Password=CloudGame#2026;TrustServerCertificate=True;
  RabbitMq__Host: "rabbitmq"
  RabbitMq__Port: "5672"
  RabbitMq__Username: "admin"
  RabbitMq__Password: "admin123"
  MSSQL_SA_PASSWORD: CloudGame#2026
