apiVersion: v1
kind: Secret
metadata:
  name: user-api-secret
type: Opaque
stringData:
  # Logging Settings
  Logging__LogLevel__Default: "Information"
  Logging__LogLevel__Microsoft.Hosting.Lifetime: "Information"

  # Jwt Settings
  JwtSettings__EncriptKey: "q8vJc0RrYx3l0m2Y0pV-09jbwqergERWGrgtrTT!!@$i2q8vJc0RrYx3l0m2Y0pV+"
  JwtSettings__Audience: "CloudGameAudience"
  JwtSettings__Issuer: "CloudGameApi"
  JwtSettings__ExpiresInMinutes: "60"

  # Database connection string
  ConnectionStrings__Default: "Server=sqlserver,1433;Database=CloudGameUser;User Id=phSvicero;Password=CloudGame#2026;TrustServerCertificate=True"

  # RabbitMQ Settings
  RabbitMq__Host: "rabbitmq"
  RabbitMq__Port: "5672"
  RabbitMq__Username: "guest"
  RabbitMq__Password: "guest"

  # Default User data
  AppDefaultUserAdmin__Email: "admin@cloudgame.com"
  AppDefaultUserAdmin__Password: "$argon2id$v=19$m=65536,t=3,p=1$8p6W85A9MT/UQo9zExtjew$2ppLR/7osayS4fMiZWZpzefUdgNhCUyVIVFrBRtOCy0"
  AppDefaultUserAdmin__Name: "Admin"

  # Serilog
  Serilog__MinimumLevel__Default: "Information"
  Serilog__MinimumLevel__Override__Microsoft: "Warning"
  Serilog__MinimumLevel__Override__System: "Warning"

  Serilog__WriteTo__0__Name: "Console"

  Serilog__WriteTo__1__Name: "File"
  Serilog__WriteTo__1__Args__path: "Logs/log-.txt"
  Serilog__WriteTo__1__Args__rollingInterval: "Day"
  Serilog__WriteTo__1__Args__retainedFileCountLimit: "30"
  Serilog__WriteTo__1__Args__outputTemplate: "[{Timestamp:yyyy-MM-dd HH:mm:ss} {Level:u3}] {SourceContext} - {Message:lj}{NewLine}{Exception}"

  Serilog__Enrich__0: "FromLogContext"
  Serilog__Enrich__1: "WithMachineName"
  Serilog__Enrich__2: "WithThreadId"