apiVersion: v1
kind: Secret
metadata:
  name: infra-secret
type: Opaque
stringData:  
  RabbitMQ__Username: admin
  RabbitMQ__Password: admin123
  MSSQL_SA_PASSWORD: CloudGame#2026
  MONGO_INITDB_DATABASE: CloudGameCache
  MONGO_INITDB_ROOT_USERNAME: root
  MONGO_INITDB_ROOT_PASSWORD: CloudGame2026
