apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sql-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqlserver
  template:
    metadata:
      labels:
        app: sqlserver
    spec:
      containers:
        - name: sqlserver
          image: mcr.microsoft.com/mssql/server:2022-latest
          ports:
            - name: sql
              containerPort: 1433
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: MSSQL_SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: payment-api-secret
                  key: MSSQL_SA_PASSWORD
          volumeMounts:
            - name: sql-data
              mountPath: /var/opt/mssql
          readinessProbe:
            tcpSocket:
              port: 1433
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 10
      volumes:
        - name: sql-data
          persistentVolumeClaim:
            claimName: sql-data
---
apiVersion: v1
kind: Service
metadata:
  name: sqlserver
spec:
  type: ClusterIP
  selector:
    app: sqlserver
  ports:
    - name: sql
      port: 1433
      targetPort: 1433
